name: AEVI API
markdown: redcarpet
highlighter: pygments
version: 2.2.0
category-list: [introduction, guides, reference, javadoc]
exclude: [build.gradle, Aevi-SDK-Documentation.iml, aws.properties, local.properties, circle.yml, publish-live.sh, publish-develop.sh, publish-check.sh, Rakefile, Gemfile, Gemfile.lock, README.md]
keep_files: [javadoc]
redcarpet:
    filter_html: false
    extensions:
      - hard_wrap
      - no_intra_emphasis
      - autolink
      - strikethrough
      - fenced_code_blocks
      - tables

baseurl:
imgbaseurl: 
jdbaseurl: ../javadoc/
offline: true